"""Goal: what the agent should prove. Run this file to test."""

import sys
sys.setrecursionlimit(100000)
sys.path.insert(0, 'src')

from core.lang import Var, In, Not, Forall, Implies
from core.derived import Exists, Eq, And, Or, Iff
from core.proof import qed, same
from core.zfc import ZFCAxiom
from vocab import (OrdPair, Successor, Empty, Singleton, PairSet,
    Subset, Inductive, Omega, Function, Apply, RecApprox, Recursive,
    ExistsUnique, Union, TotalFrom, Plus, Num)
from tm import add_goal
tm_add_goal = add_goal()

is_axiom = lambda f: isinstance(f, ZFCAxiom)

import theorems

# fresh vars for goal formulas
a, b, c, d, t, p = Var(), Var(), Var(), Var(), Var(), Var()
x, y, z, w, s, n = Var(), Var(), Var(), Var(), Var(), Var()
q, r = Var(), Var()
A, B, C = In(x,y), In(y,z), In(z,w)

goals = [
    # --- logic ---
    ('modus_ponens',
     lambda: theorems.modus_ponens(A, B, [x,y,z]),
     Forall(z, Forall(y, Forall(x, Implies(A, Implies(Implies(A,B), B)))))),
    ('double_negation',
     lambda: theorems.double_negation(A, [x,y]),
     Forall(y, Forall(x, Implies(A, Not(Not(A)))))),
    ('forall_instantiation',
     lambda: theorems.forall_instantiation(x, A, z, [y,z]),
     Forall(z, Forall(y, Implies(Forall(x, A), In(z,y))))),
    ('unique_empty',
     lambda: theorems.unique_empty(),
     Forall(a, Implies(Empty(a), Forall(b, Implies(Empty(b), Eq(a,b)))))),
    ('eq_reflexive',
     lambda: theorems.eq_reflexive(),
     Forall(a, Eq(a,a))),
    ('iff_intro',
     lambda: theorems.iff_intro(A, B, [x,y,z]),
     Forall(z, Forall(y, Forall(x, Implies(Implies(A,B), Implies(Implies(B,A), Iff(A,B))))))),
    ('iff_elim_left',
     lambda: theorems.iff_elim_left(A, B, [x,y,z]),
     Forall(z, Forall(y, Forall(x, Implies(Iff(A,B), Implies(A,B)))))),
    ('iff_elim_right',
     lambda: theorems.iff_elim_right(A, B, [x,y,z]),
     Forall(z, Forall(y, Forall(x, Implies(Iff(A,B), Implies(B,A)))))),
    ('eq_symmetric',
     lambda: theorems.eq_symmetric(),
     Forall(a, Forall(b, Implies(Eq(a,b), Eq(b,a))))),
    ('eq_transitive',
     lambda: theorems.eq_transitive(),
     Forall(a, Forall(b, Forall(c, Implies(Eq(a,b), Implies(Eq(b,c), Eq(a,c))))))),
    ('or_elim',
     lambda: theorems.or_elim(A, B, C, [x,y,z,w]),
     Forall(w, Forall(z, Forall(y, Forall(x, Implies(Or(A,B), Implies(Implies(A,C), Implies(Implies(B,C), C)))))))),
    ('eq_substitution',
     lambda: theorems.eq_substitution(),
     Forall(a, Forall(b, Forall(c, Implies(Eq(a,b), Iff(In(a,c), In(b,c))))))),
    ('and_intro',
     lambda: theorems.and_intro(A, B, [x,y,z]),
     Forall(z, Forall(y, Forall(x, Implies(A, Implies(B, And(A,B))))))),
    ('and_elim_left',
     lambda: theorems.and_elim_left(A, B, [x,y,z]),
     Forall(z, Forall(y, Forall(x, Implies(And(A,B), A))))),
    ('and_elim_right',
     lambda: theorems.and_elim_right(A, B, [x,y,z]),
     Forall(z, Forall(y, Forall(x, Implies(And(A,B), B))))),
    ('or_intro_left',
     lambda: theorems.or_intro_left(A, B, [x,y,z]),
     Forall(z, Forall(y, Forall(x, Implies(A, Or(A,B)))))),
    ('or_intro_right',
     lambda: theorems.or_intro_right(A, B, [x,y,z]),
     Forall(z, Forall(y, Forall(x, Implies(B, Or(A,B)))))),
    ('char_transfer',
     lambda: theorems.char_transfer(A, B, C, [x,y,z,w]),
     Forall(w, Forall(z, Forall(y, Forall(x, Implies(Iff(A,B), Implies(Iff(B,C), Iff(A,C)))))))),
    ('iff_sym',
     lambda: theorems.iff_sym(A, B, [x,y,z]),
     Forall(z, Forall(y, Forall(x, Implies(Iff(A,B), Iff(B,A)))))),
    ('iff_mp',
     lambda: theorems.iff_mp(A, B, [x,y,z]),
     Forall(z, Forall(y, Forall(x, Implies(Iff(A,B), Implies(A,B)))))),
    ('iff_mp_rev',
     lambda: theorems.iff_mp_rev(A, B, [x,y,z]),
     Forall(z, Forall(y, Forall(x, Implies(Iff(A,B), Implies(B,A)))))),
    ('or_iff_compat',
     lambda: theorems.or_iff_compat(A, B, C, In(x,w), [x,y,z,w]),
     Forall(w, Forall(z, Forall(y, Forall(x,
         Implies(Iff(A,C), Implies(Iff(B,In(x,w)), Iff(Or(A,B), Or(C,In(x,w)))))))))),
    ('eq_transfer',
     lambda: theorems.eq_transfer(),
     Forall(a, Forall(b, Forall(z, Implies(Eq(a,b), Iff(In(z,a), In(z,b))))))),
    ('iff_chain',
     lambda: theorems.iff_chain(A, B, In(x,z), [x,y,z]),
     Forall(z, Forall(y, Forall(x, Implies(Iff(A,B), Implies(Iff(B,In(x,z)), Iff(A,In(x,z)))))))),
    ('forall_implies_exists',
     lambda: theorems.forall_implies_exists(A, B, x, [y,z]),
     Forall(z, Forall(y, Implies(Forall(x, Implies(A,B)), Implies(Exists(x,A), Exists(x,B)))))),
    # --- sets ---
    ('singleton_exists',
     lambda: theorems.singleton_exists(),
     Forall(a, Exists(s, Singleton(s,a)))),
    ('singleton_eq',
     lambda: theorems.singleton_eq(),
     Forall(a, Forall(b, Forall(s, Implies(Singleton(s,a), Implies(Singleton(s,b), Eq(a,b))))))),
    ('singleton_injection',
     lambda: theorems.singleton_injection(),
     Forall(a, Forall(b, Implies(Forall(x, Iff(Eq(x,a), Eq(x,b))), Eq(a,b))))),
    ('pair_injection',
     lambda: theorems.pair_injection(),
     Forall(a, Forall(b, Forall(c, Forall(d,
         Implies(Forall(x, Iff(Or(Eq(x,a),Eq(x,b)), Or(Eq(x,c),Eq(x,d)))),
                 Or(And(Eq(a,c),Eq(b,d)), And(Eq(a,d),Eq(b,c))))))))),
    ('singleton_pair_eq',
     lambda: theorems.singleton_pair_eq(),
     Forall(a, Forall(b, Forall(c,
         Implies(Forall(x, Iff(Eq(x,a), Or(Eq(x,b),Eq(x,c)))), And(Eq(b,a),Eq(c,a))))))),
    ('tuple_injection',
     lambda: theorems.tuple_injection(),
     Forall(a, Forall(b, Forall(c, Forall(d, Forall(t,
         Implies(OrdPair(t,a,b), Implies(OrdPair(t,c,d), And(Eq(a,c),Eq(b,d)))))))))),
    ('kuratowski',
     lambda: theorems.kuratowski(),
     Forall(a, Forall(b, Forall(c, Forall(d, Forall(t,
         Implies(OrdPair(t,a,b), Forall(s,
             Implies(OrdPair(s,c,d), Implies(Eq(t,s), And(Eq(a,c),Eq(b,d)))))))))))),
    ('successor_exists',
     lambda: theorems.successor_exists(),
     Forall(n, Exists(s, Successor(s,n)))),
    ('union_exists',
     lambda: theorems.union_exists(),
     Forall(a, Forall(b, Exists(s, Forall(x, Iff(In(x,s), Or(In(x,a),In(x,b)))))))),
    ('unique_successor',
     lambda: theorems.unique_successor(),
     Forall(n, Forall(a, Forall(b, Implies(Successor(a,n), Implies(Successor(b,n), Eq(a,b))))))),
    ('eq_in_eq',
     lambda: theorems.eq_in_eq(),
     Forall(a, Forall(b, Implies(Eq(a,b), Forall(z, Iff(Eq(z,a), Eq(z,b))))))),
    ('ordpair_exists',
     lambda: theorems.ordpair_exists(),
     Forall(x, Forall(y, Exists(p, OrdPair(p,x,y))))),
    ('succ_not_empty',
     lambda: theorems.succ_not_empty(),
     Forall(n, Forall(s, Implies(Successor(s,n), Not(Empty(s)))))),
    ('ordpair_eq_transfer',
     lambda: theorems.ordpair_eq_transfer(),
     Forall(a, Forall(b, Forall(c, Forall(d, Forall(t,
         Implies(Eq(a,c), Implies(Eq(b,d), Implies(OrdPair(t,a,b), OrdPair(t,c,d)))))))))),
    ('ordpair_val_transfer',
     lambda: theorems.ordpair_val_transfer(),
     Forall(t, Forall(a, Forall(b, Forall(c,
         Implies(Eq(b,c), Implies(OrdPair(t,a,b), OrdPair(t,a,c)))))))),
    ('ordpair_unique',
     lambda: theorems.ordpair_unique(),
     Forall(a, Forall(b, Forall(t, Forall(s,
         Implies(OrdPair(t,a,b), Implies(OrdPair(s,a,b), Eq(t,s)))))))),
    ('ordpair_set_transfer',
     lambda: theorems.ordpair_set_transfer(),
     Forall(a, Forall(b, Forall(c, Forall(d,
         Implies(Eq(a,b), Implies(OrdPair(b,c,d), OrdPair(a,c,d)))))))),
    ('eq_successor_transfer',
     lambda: theorems.eq_successor_transfer(),
     Forall(a, Forall(b, Forall(c, Forall(d,
         Implies(Eq(a,c), Implies(Eq(b,d), Implies(Successor(c,d), Successor(a,b))))))))),
    # --- omega ---
    ('omega_is_inductive',
     lambda: theorems.omega_is_inductive(),
     Forall(a, Implies(Omega(a), Inductive(a)))),
    ('omega_contains_empty',
     lambda: theorems.omega_contains_empty(),
     Forall(a, Implies(Omega(a), Forall(b, Implies(Empty(b), In(b,a)))))),
    ('omega_succ_closed',
     lambda: theorems.omega_succ_closed(),
     Forall(a, Implies(Omega(a), Forall(b, Implies(In(b,a), Forall(c, Implies(Successor(c,b), In(c,a)))))))),
    ('omega_smallest_inductive',
     lambda: theorems.omega_smallest_inductive(),
     Forall(a, Forall(b, Implies(Omega(b), Implies(And(Subset(a,b), Inductive(a)), Eq(a,b)))))),
    ('omega_exists',
     lambda: theorems.omega_exists(),
     Exists(a, Omega(a))),
    ('omega_unique',
     lambda: theorems.omega_unique(),
     Forall(a, Forall(b, Implies(Omega(a), Implies(Omega(b), Forall(z, Iff(In(z,a), In(z,b)))))))),
    # --- recursion ---
    ('func_unique_thm',
     lambda: theorems.func_unique_thm(),
     Forall(a, Forall(b, Forall(c, Forall(d,
         Implies(Function(a), Implies(Apply(a,b,c), Implies(Apply(a,b,d), Eq(c,d))))))))),
    ('successor_injection',
     lambda: theorems.successor_injection(),
     Forall(a, Forall(b, Forall(c,
         Implies(Successor(c,a), Implies(Successor(c,b), Eq(a,b))))))),
    ('succ_func_exists',
     lambda: theorems.succ_func_exists(),
     Forall(w, Exists(s, Forall(x,
         Iff(In(x,s), Exists(n, And(In(n,w), Exists(t, And(Successor(t,n), OrdPair(x,n,t)))))))))),
    ('rec_approx_zero',
     lambda: theorems.rec_approx_zero(),
     Forall(a, Forall(b, Forall(c, Forall(d, Forall(t, Forall(s,
         Implies(RecApprox(a,b,c,d), Implies(Empty(t), Implies(Apply(a,t,s), Eq(s,b))))))))))),
    ('func_preserves_eq',
     lambda: theorems.func_preserves_eq(),
     Forall(a, Forall(b, Forall(c, Forall(d, Forall(s,
         Implies(Function(s), Implies(Eq(a,b), Implies(Apply(s,a,c),
             Implies(Apply(s,b,d), Eq(c,d))))))))))),
    ('rec_func_exists',
     lambda: theorems.rec_func_exists(),
     Forall(a, Forall(b, Forall(c,
         Implies(Function(b), Implies(TotalFrom(b,a),
             Implies(Omega(c),
                 Exists(s, Forall(p, Iff(In(p,s),
                     Exists(n, And(In(n,c),
                         Exists(d, Exists(t, And(And(RecApprox(d,a,b,c), Apply(d,n,t)),
                             OrdPair(p,n,t))))))))))))))))  ,
    ('recursion_theorem',
     lambda: theorems.recursion_theorem(),
     Forall(a, Forall(b, Forall(c,
         Implies(Function(b), Implies(TotalFrom(b,a), Implies(Omega(c),
             ExistsUnique(s, Recursive(s,a,b,c))))))))),
    ('rec_unique',
     lambda: theorems.rec_unique(),
     Forall(a, Forall(b, Forall(c, Forall(d, Forall(s,
         Implies(TotalFrom(b,a), Implies(Omega(c), Implies(Recursive(d,a,b,c),
             Implies(Recursive(s,a,b,c), Eq(d,s))))))))))),
    # --- arithmetic ---
    ('unique_num_0',
     lambda: theorems.unique_num(0),
     ExistsUnique(a, Num(a, 0))),
    ('unique_num_1',
     lambda: theorems.unique_num(1),
     ExistsUnique(a, Num(a, 1))),
    ('unique_num_2',
     lambda: theorems.unique_num(2),
     ExistsUnique(a, Num(a, 2))),
    ('plus_zero_right',
     lambda: theorems.plus_zero_right(),
     Forall(w, Forall(a, Forall(b, Forall(c, Forall(d,
         Implies(Omega(w), Implies(In(a,w), Implies(Num(b,0),
             Implies(Plus(a,b,c), Eq(c,a))))))))))),
    ('plus_zero_left',
     lambda: theorems.plus_zero_left(),
     Forall(w, Forall(a, Forall(b, Forall(c,
         Implies(Omega(w), Implies(In(a,w), Implies(Num(b,0),
             Implies(Plus(b,a,c), Eq(c,a)))))))))),
    ('plus_comm',
     lambda: theorems.plus_comm(),
     Forall(w, Forall(a, Forall(b, Forall(c,
         Implies(Omega(w), Implies(In(a,w), Implies(In(b,w),
             Implies(Plus(a,b,c), Plus(b,a,c)))))))))),
    ('plus_assoc',
     lambda: theorems.plus_assoc(),
     Forall(w, Forall(a, Forall(b, Forall(c, Forall(d, Forall(s, Forall(t,
         Implies(Omega(w), Implies(In(a,w), Implies(In(b,w), Implies(In(c,w),
             Implies(Plus(a,b,d), Implies(Plus(d,c,s),
                 Implies(Plus(b,c,t), Plus(a,t,s))))))))))))))))  ,
    ('prove_2_plus_2',
     lambda: theorems.prove_addition(2, 2),
     Forall(w, Forall(a, Forall(b, Forall(c,
         Implies(Omega(w), Implies(Num(a,2), Implies(Num(b,2),
             Implies(Num(c,4), Plus(a,b,c)))))))))),
    # --- turing machine ---
    ('tm_add_correct',
     None,  # theorem not yet written
     tm_add_goal),
]

if __name__ == '__main__':
    select = set(sys.argv[1:]) if len(sys.argv) > 1 else None
    passed = 0
    failed = []
    for name, build, expected in goals:
        if select and name not in select:
            continue
        try:
            proof = build()
            assert same(proof.sequent.right[0], expected, expand=False), \
                f'wrong theorem: {proof.sequent.right[0]}'
            assert qed(proof, is_axiom), 'qed failed'
            passed += 1
        except Exception as e:
            failed.append(name)
            print(f'{name}: {e}')
    total = len([n for n,_,_ in goals if not select or n in select])
    print(f'\n{passed}/{total} passed')
    if failed:
        print(f'failed: {", ".join(failed)}')
